name: 'offline.mall::lang.common.category'
modelClass: OFFLINE\Mall\Models\Category
form: $/offline/mall/models/category/fields.yaml
defaultRedirect: offline/mall/categories
create:
    title: 'offline.mall::lang.titles.categories.create'
    redirect: 'offline/mall/categories/update/:id'
    redirectClose: offline/mall/categories
update:
    title: 'offline.mall::lang.titles.categories.update'
    redirect: offline/mall/categories
    redirectClose: offline/mall/categories
preview:
    title: 'offline.mall::lang.titles.categories.preview'
