name: 'offline.mall::lang.common.customer_groups'
modelClass: OFFLINE\Mall\Models\CustomerGroup
form: $/offline/mall/models/customergroup/fields.yaml
defaultRedirect: offline/mall/customergroups
create:
    title: 'offline.mall::lang.titles.customer_groups.create'
    redirect: 'offline/mall/customergroups/update/:id'
    redirectClose: offline/mall/customergroups
update:
    title: 'offline.mall::lang.titles.customer_groups.update'
    redirect: offline/mall/customergroups
    redirectClose: offline/mall/customergroups
